main: com.townanim.TownAnimation
name: TownAnimation
author: Nosiume
version: 1.0
commands:
  createnpc:
    description: Creates an npc at your current position
    usage: §cUsage is /createnpc <ign>.
    permission: townanim
  path:
    description: Creates a path of desired name and allows you to then build it from scratch !
    usage: §cUsage is /path <name>
    permission: townanim
  pathlist:
    description: Lists all the available paths.
    permission: townanim
  deletepath:
    description: Deletes a path by it's name.
    usage: §cUsage is /deletepath <name>
    permission: townanim